---
title: "Collective Emotions and Social Resilience in the Digital Traces After a Terrorist Attack"
author: "David García and Bernard Rimé"
date: "August 31st, 2018 (refactored on October 10th, 2022)"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
---

# 1. Data description

```{r Setup, cache=FALSE, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
library(sfsmisc)
library(ggplot2)
library(zoo)
library(dplyr)
library(magrittr)
library(arm)
library(texreg)
Sys.setlocale("LC_ALL", 'en_US.UTF-8')
source("Scripts/AuxFunctions.R")
```

```{r volumeTS, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}
load("Data/Tweets.RData")
Tweets %>% mutate(day=as.Date(date)) -> Tweets
Tweets$user <- Tweets$userid
Tweets %>% group_by(date) -> Tweets
print(paste("N tweets:",nrow(Tweets))) # 7666170
Tweets %>% filter(date>="2015-04-01" & date < "2015-10-01")-> TweetsBL
TweetsBL %>% mutate(w=weekdays(as.Date(date))) -> TweetsBL
print(paste("N tweets in baseline:",nrow(TweetsBL))) # 7666170
TweetsBL %>% group_by(date) %>% summarise(nt=length(n)) %>% summarise(mntw=mean(nt)) -> ntweetsBL
Tweets %>% summarise(ntweets=length(n)) -> dts
dts$bl <- rep(ntweetsBL$mntw, length(dts$ntweets))
```

```{r plotvolumeTSPub, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=7, fig.height=3}
dts %>% filter(date >= "2015-10-16"  & date < "2015-12-12") -> dts2

print(paste("N tweets in window:",sum(dts2$ntweets))) # 2766054
plt <- ggplot()
plt <- plt + geom_line(data = dts2, mapping=aes(x=as.Date(date), y=ntweets))
plt <- plt + geom_point(data = dts2, mapping=aes(x=as.Date(date), y=ntweets))
plt <- plt + scale_x_date("Day", date_breaks = "2 weeks") +
      scale_y_continuous(name="Amount of tweets", breaks=seq(20000,100000,20000), 
                           labels=c("20K","40K","60K","80K","100K")) +
      expand_limits(y=c(35000,100000))
plt <- plt + theme_bw() + geom_vline(xintercept=as.numeric(as.Date("2015-11-13")),
                                     col=rgb(1,0,0,0.5), lwd=1, lty=2) 
plt <- plt + geom_hline(yintercept = dts$bl[1], col=rgb(0,0,0,0.5), lwd=1,lty=2) 
plt
```

# 2. Affective Reactions

```{r emorun,cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE,fig.width=8, fig.height=8}
TweetsBL %>% group_by(w) %>%summarise(bl=mean(posemo/n)) -> posBL
TweetsBL %>% group_by(w) %>%summarise(bl=mean(negemo/n)) -> negBL

Tweets %>% filter(as.Date(date) >= "2015-10-16"  & as.Date(date) < "2015-12-12") -> Tsel
posts <- ciTS(Tsel, "posemo", R=10000)
posts$w <- weekdays(as.Date(posts$date))
posts <- inner_join(posts, posBL)
save(posts, file="temp/posemoCITS.RData")

negts <- ciTS(Tsel, "negemo", R=10000)
negts$w <- weekdays(as.Date(negts$date))
negts <- inner_join(negts, negBL)
save(negts, file="temp/negemoCITS.RData")
```

```{r plotValuesTSFit, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=8, fig.height=3, results="asis"}
load("temp/posemoCITS.RData")
load("temp/negemoCITS.RData")

d1 <- as.Date("2015-11-13")
dtbreaks <- c(d1 + seq(-27,0,by=3), d1 + seq(3,27,by=3))

plt <- plotts(ts=posts, ylab="Affect Terms", col="darkblue", bgcolor = rgb(0,0,1,0.25))
plt <- plotts(ts=negts, col="darkred", bgcolor = rgb(1,0,0,0.25), plt=plt)
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d")
plt <- plt + theme(axis.text.x = element_text(angle = 30, hjust = 1, colour = "black", size = 10))

Zday <- which(posts$date == "2015-11-13")[1]
negFit <- TSmodel1(log(negts$mid/negts$bl), Zday)
negDF <- data.frame(x=negts$date[2:length(negts$date)],y=negFit$fitted.values)
plt <- plt + geom_line(data=negDF, aes(x=as.Date(x),y=y), col= rgb(1,0,0), lty=2)

posFit <- TSmodel1(log(posts$mid/posts$bl), Zday)
posDF <- data.frame(x=posts$date[2:length(posts$date)],y=posFit$fitted.values)
plt <- plt + geom_line(data=posDF, aes(x=as.Date(x),y=y), col= rgb(0,0,1), lty=2)

plt

texreg(list(posFit, negFit), custom.model.names = c("PA","NA"), 
       digits=4, bold=0.05)
```

```{r EmoModelDiags, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}
simulates <- coef(sim(posFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

library(tseries)
confint.default(posFit)
summ <- summary(posFit)
print(paste("Positive terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(posFit$residuals)
kpss.test(posFit$residuals)
cor.test(sqrt(abs(posFit$residuals)), posFit$fitted.values)

simulates <- coef(sim(negFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

confint.default(negFit)
summ <- summary(negFit)
print(paste("Negative terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(negFit$residuals)
kpss.test(negFit$residuals)
cor.test(sqrt(abs(negFit$residuals)), negFit$fitted.values)
```


```{r negsrun,cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE,fig.width=8, fig.height=8}
TweetsBL %>% group_by(w)  %>% summarise(bl=mean(sad/n)) -> sadBL
TweetsBL %>% group_by(w) %>% summarise(bl=mean(ang/n)) -> angBL
TweetsBL %>% group_by(w) %>% summarise(bl=mean(anx/n)) -> anxBL

angts <- ciTS(Tsel, "ang", R=10000)
angts$w <- weekdays(as.Date(angts$date))
angts <- inner_join(angts, angBL)
save(angts, file="temp/angCITS.RData")

anxts <- ciTS(Tsel, "anx", R=10000)
anxts$w <- weekdays(as.Date(anxts$date))
anxts <- inner_join(anxts, anxBL)
save(anxts, file="temp/anxCITS.RData")

sadts <- ciTS(Tsel, "sad", R=10000)
sadts$w <- weekdays(as.Date(sadts$date))
sadts <- inner_join(sadts, sadBL)
save(sadts, file="temp/sadCITS.RData")
```

```{r EmoPlotFits2, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=8, fig.height=3, results="asis"}
load("temp/anxCITS.RData")
load("temp/angCITS.RData")
load("temp/sadCITS.RData")

plt <- plotts(ts=sadts, ylab="Negative Affect Terms", 
              col="darkblue", bgcolor = rgb(0,0,1,0.25))
plt <- plotts(ts=angts, col="darkred", bgcolor = rgb(1,0,0,0.25), plt=plt)
plt <- plotts(ts=anxts, col="darkorange", bgcolor = rgb(1,140/255,0,0.25), plt=plt)

Zday <- which(posts$date == "2015-11-13")[1]
sadFit <- TSmodel1(log(sadts$mid/sadts$bl), Zday)
DF <- data.frame(x=sadts$date[2:length(sadts$date)],y=sadFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(0,0,1), lty=2)

angFit <- TSmodel1(log(angts$mid/angts$bl), Zday)
DF <- data.frame(x=angts$date[2:length(angts$date)],y=angFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(1,0,0), lty=2)

anxFit <- TSmodel1(log(anxts$mid/anxts$bl), Zday)
DF <- data.frame(x=anxts$date[2:length(anxts$date)],y=anxFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(1,140/255,0), lty=2)

plt

texreg(list(sadFit, angFit, anxFit), 
       custom.model.names = c("Sadness","Anger","Anxiety"), 
       digits=4, bold=0.05)

```

```{r NegModelDiags, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}
simulates <- coef(sim(sadFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

summ <- summary(sadFit)
confint.default(sadFit)
print(paste("Sadness terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(sadFit$residuals)
kpss.test(sadFit$residuals)
cor.test(sqrt(abs(sadFit$residuals)), sadFit$fitted.values)

simulates <- coef(sim(angFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

summ <- summary(angFit)
confint.default(angFit)
print(paste("Anger terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(angFit$residuals)
kpss.test(angFit$residuals)
cor.test(sqrt(abs(angFit$residuals)), angFit$fitted.values)


simulates <- coef(sim(anxFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

summ <- summary(anxFit)
confint.default(anxFit)
print(paste("Anxiety terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(anxFit$residuals)
kpss.test(anxFit$residuals)
cor.test(sqrt(abs(anxFit$residuals)), anxFit$fitted.values)
```




# 3. Social processes

```{r socialrun,cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE,fig.width=8, fig.height=8}

TweetsBL %>% group_by(w) %>%summarise(bl=mean(soc/n)) -> SocBL
TweetsBL %>% group_by(w) %>%summarise(bl=mean(prosoc/n)) -> ProSocBL
TweetsBL %>% group_by(w) %>%summarise(bl=mean(frenchValues/n)) -> FVBL

Socts <- ciTS(Tsel, "soc", R=10000)
Socts$w <- weekdays(as.Date(Socts$date))
Socts <- inner_join(Socts, SocBL)
save(Socts, file="temp/SocCITS.RData")

ProSocts <- ciTS(Tsel, "prosoc", R=10000)
ProSocts$w <- weekdays(as.Date(ProSocts$date))
ProSocts <- inner_join(ProSocts, ProSocBL)
save(ProSocts, file="temp/ProSocCITS.RData")

FVts <- ciTS(Tsel, "frenchValues", R=10000)
FVts$w <- weekdays(as.Date(FVts$date))
FVts <- inner_join(FVts, FVBL)
save(FVts, file="temp/frenchValuesCITS.RData")
```

```{r plotValuesTSPubSocFit, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=8, fig.height=2.5, results="asis"}
load("temp/SocCITS.RData")

plt <- plotts(ts=Socts, ylab="Social Process Terms", 
              col="darkorange", bgcolor = rgb(1,144/255,0,0.25))

Zday <- which(Socts$date == "2015-11-13")[1]
SocFit <- TSmodel1(log(Socts$mid/Socts$bl), Zday)
DF <- data.frame(x=Socts$date[2:length(Socts$date)],y=SocFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(1,144/255,0), lty=2)

plt
texreg(SocFit, custom.model.names = c("Social"), digits=4, bold=0.05)
```


```{r plotValuesTSPubSocFit2, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}

simulates <- coef(sim(SocFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))

summ <- summary(SocFit)
confint.default(SocFit)
print(paste("Social process terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(SocFit$residuals)
kpss.test(SocFit$residuals)
cor.test(sqrt(abs(SocFit$residuals)), SocFit$fitted.values)
```


```{r plotValuesTSPubFrenchFit, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=8, fig.height=2.5, results="asis"}
load("temp/frenchValuesCITS.RData")
plt <- plotts(ts=FVts, ylab="French Values Terms", 
              col="darkblue", bgcolor = rgb(0,0,0.75,0.25))

Zday <- which(FVts$date == "2015-11-13")[1]
FVFit <- TSmodel1(log(FVts$mid/FVts$bl), Zday)
DF <- data.frame(x=FVts$date[2:length(FVts$date)],y=FVFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(0,0,144/255), lty=2)
plt
texreg(FVFit, custom.model.names = c("French Values Terms"), digits=4, bold=0.05)
```

```{r plotValuesTSPubFrenchFit2, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}


simulates <- coef(sim(FVFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))


summ <- summary(FVFit)
confint.default(FVFit)
print(paste("French Values terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(FVFit$residuals)
kpss.test(FVFit$residuals)
cor.test(sqrt(abs(FVFit$residuals)), FVFit$fitted.values)
```


```{r plotValuesTSPubProSoc, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.width=8, fig.height=2.5, results="asis"}
load("temp/ProSocCITS.RData")
plt <- plotts(ts=ProSocts, ylab="Prosocial Terms", 
              col="darkgreen", bgcolor = rgb(0,0.75,0,0.25))

Zday <- which(ProSocts$date == "2015-11-13")[1]
ProSocFit <- TSmodel1(log(ProSocts$mid/ProSocts$bl), Zday)
DF <- data.frame(x=ProSocts$date[2:length(ProSocts$date)],y=ProSocFit$fitted.values)
plt <- plt + geom_line(data=DF, aes(x=as.Date(x),y=y), col= rgb(0,0,144/255), lty=2)
plt
texreg(ProSocFit, custom.model.names = c("Prosocial Terms"), digits=4, bold=0.05)
```

```{r plotValuesTSPubProSoc2, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}

simulates <- coef(sim(ProSocFit, n.sims=20000))
print("Intercept:")
quantile(simulates[10001:20000,1], probs = c(0.025, 0.5, 0.975))
print("ypre:postFALSE")
quantile(simulates[10001:20000,2], probs = c(0.025, 0.5, 0.975))
print("ypre:postTRUE")
quantile(simulates[10001:20000,3], probs = c(0.025, 0.5, 0.975))
print("zTRUE")
quantile(simulates[10001:20000,4], probs = c(0.025, 0.5, 0.975))
print("z2TRUE")
quantile(simulates[10001:20000,5], probs = c(0.025, 0.5, 0.975))


summ <- summary(ProSocFit)
confint.default(ProSocFit)
print(paste("prosocial terms model R2:", (1-summ$deviance/summ$null.deviance)))
shapiro.test(ProSocFit$residuals)
kpss.test(ProSocFit$residuals)
cor.test(sqrt(abs(ProSocFit$residuals)), ProSocFit$fitted.values)
```


# 4. Emotional Synchronization Effect

```{r ReadDataSynch, cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE}
Tweets$emo <- Tweets$posemo + Tweets$negemo

Tweets %>% filter(date>="2015-11-13" & date <= "2015-11-27")-> TweetsDFAttack
TweetsDFAttack %>% group_by(userid) -> TweetsDFAttack
TweetsDFAttack %>% summarise(avgEmo=mean((posemo+negemo)/n), nT=n()/15, # 15 days after the attacks
                             avgSoc=mean(soc/n), avgProsoc=mean(prosoc/n),
                             avgFV=mean(frenchValues/n), avgPA=mean(posemo/n), avgNA=mean(negemo/n),
                             avgAng=mean(ang/n), avgAnx = mean(anx/n), avgSad=mean(sad/n)) -> userDF

Tweets %>% filter(date>="2015-08-13" & date <= "2015-11-12")-> TweetsDFBL
TweetsDFBL %>% group_by(userid) -> TweetsDFBL
TweetsDFBL %>% summarise(nTBL = length(n)/92,  # number of days in baseline period
                         avgEmoBL=mean((posemo+negemo)/n), socBL=mean(soc/n),  prosocBL=mean(prosoc/n), 
                         FVBL=mean(frenchValues/n),
                         PABL=mean(posemo/n), NABL=mean(negemo/n),
                         anxBL=mean(anx/n), sadBL=mean(sad/n), angerBL=mean(ang/n), iBL=mean(i/n)) -> userDFBL

userDF <- full_join(userDF, userDFBL, by="userid")

Tweets %>% filter(date>="2015-11-28" & date <= "2016-02-27")-> TweetsDFPost
TweetsDFPost %>% group_by(userid) -> TweetsDFPost
TweetsDFPost %>% summarise( nTpost=n(),
  PAPost = mean(posemo/n),  NAPost = mean(negemo/n),
  anxPost = mean(anx/n),  sadPost = mean(sad/n), angPost = mean(ang/n),  
  EmoPost = mean((posemo+negemo)/n),
  socPost=mean(soc/n), prosocPost =mean(prosoc/n), FVPost = mean(frenchValues/n)) -> userDFPost
userDF <- full_join(userDF, userDFPost, by="userid")

save(userDF, file="temp/userDF.RData")

sel <- data.frame(userid=userDF$userid, sel=userDF$avgEmo>userDF$avgEmoBL)
sel$user <- sel$userid

pTS <- PairTSW(Tweets, sel, "soc", R=1000,w=30)
save(pTS, file="temp/SynchSoc.RData")

pTS <- PairTSDifW(Tweets, sel, "soc", R=1000,w=30)
save(pTS, file="temp/SynchDifSoc.RData")

pTS <- PairTSW(Tweets, sel, "prosoc", R=1000,w=30)
save(pTS, file="temp/SynchProSoc.RData")

pTS <- PairTSDifW(Tweets, sel, "prosoc", R=1000,w=30)
save(pTS, file="temp/SynchDifProSoc.RData")

pTS <- PairTSW(Tweets, sel, "frenchValues", R=1000,w=30)
save(pTS, file="temp/SynchFV.RData")

pTS <- PairTSDifW(Tweets, sel, "frenchValues", R=1000,w=30)
save(pTS, file="temp/SynchDifFV.RData")
```

```{r , cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE}
load("temp/userDF.RData")
attach(userDF)

sum(!is.na(nT) & nT>0)
sum(!is.na(nTBL) & nTBL>0)
sum(!is.na(nTpost) & nTpost>0)
sum((!is.na(nT) & nT>0) & (!is.na(nTBL) & nTBL>0) & (!is.na(nTpost) & nTpost>0))

periodUserDF <- subset(userDF, (!is.na(nT) & nT>0) & (!is.na(nTBL) & nTBL>0) & (!is.na(nTpost) & nTpost>0))
save(periodUserDF, file="temp/periodUserDF.RData")

```

## 4.0.1 Self-selection

```{r SS1, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, results="asis"}
load("temp/periodUserDF.RData")
periodUserDF %>% dplyr::select(avgEmo, PABL, NABL, socBL, iBL, nTBL) -> cDF

lin <- bayesglm(avgEmo ~ PABL+NABL+socBL+iBL+log(nTBL), data=cDF)

texreg(lin, digits=4, bold=0.05, caption="Self-selection model based on personality correlates")
```

```{r SSX, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}
confint(lin)
summ <- summary(lin)
print(paste("Self-selection model R2:", (1-summ$deviance/summ$null.deviance)))
```

## 4.1 Difference time series visualizations

```{r EmoSocTS, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="Social Process Terms Synchronization", fig.width=4, fig.height=4}
load("temp/SynchSoc.RData")

d1 <- as.Date("2015-11-13")
dtbreaks <- c(d1 + seq(-4*7*8,0,by=7*4), d1 + seq(7*8,4*7*8,by=7*4))

Tts <- data.frame(date=pTS$date, mid=pTS$Tmid*100, low=pTS$Tlow*100, hi=pTS$Thi*100)
Fts <- data.frame(date=pTS$date, mid=pTS$Fmid*100, low=pTS$Flow*100, hi=pTS$Fhi*100)
plt <- plotts(Tts, nolog=TRUE,
              zero=FALSE, dtbreaks= "4 weeks", col="red", bgcolor = rgb(1,0,0,0.25))
plt <- plotts(Fts, col="blue", nolog=TRUE, add=TRUE, plt=plt, 
             bgcolor= rgb(0,0,1,0.25), zero=FALSE)
plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d", limits=c(as.Date("2015-06-30"), as.Date("2016-06-30")))
plt

```

```{r EmoSocTSDif, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="Social Process Terms Synchronization", fig.width=8, fig.height=2.5}
load("temp/SynchSoc.RData")
refTS <- pTS
load("temp/SynchDifSoc.RData")
pTS$low <- pTS$low/refTS$Flow*100
pTS$mid <- pTS$mid/refTS$Fmid*100
pTS$hi <- pTS$hi/refTS$Fhi*100

plt <- plotts(pTS, nolog=TRUE,  bgcolor= rgb(0.95,0.75,0,0.25), col="darkorange",
              zero=TRUE)
plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d", limits=c(as.Date("2015-06-30"), as.Date("2016-06-30")))
plt

```


```{r EmoProSocTS, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="Prosocial Terms Synchronization", fig.width=4, fig.height=4}
load("temp/SynchProSoc.RData")
d1 <- as.Date("2015-11-13")
dtbreaks <- c(d1 + seq(-4*7*8,0,by=7*8), d1 + seq(7*8,4*7*8,by=7*8))

Tts <- data.frame(date=pTS$date, mid=pTS$Tmid, low=pTS$Tlow, hi=pTS$Thi)
Fts <- data.frame(date=pTS$date, mid=pTS$Fmid, low=pTS$Flow, hi=pTS$Fhi)
plt <- plotts(Tts, nolog=TRUE,
              zero=FALSE, dtbreaks= "8 weeks", col="red", bgcolor = rgb(1,0,0,0.25))
plt <- plotts(Fts, col="blue", nolog=TRUE, add=TRUE, plt=plt, 
             bgcolor= rgb(0,0,1,0.25), zero=FALSE)
plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d")
plt
```

```{r EmoProSocTSDif, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="Prosocial Terms Synchronization", fig.width=8, fig.height=2.5}
load("temp/SynchProSoc.RData")
refTS <- pTS
load("temp/SynchDifProSoc.RData")
pTS$low <- pTS$low/refTS$Flow*100
pTS$mid <- pTS$mid/refTS$Fmid*100
pTS$hi <- pTS$hi/refTS$Fhi*100

plt <- plotts(pTS, nolog=TRUE,  bgcolor= rgb(0,0.5,0,0.25), col="darkgreen",
              zero=TRUE)
plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d", limits=c(as.Date("2015-06-30"), as.Date("2016-06-30")))
plt

```

```{r EmoFVTS, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="French Value Terms Synchronization", fig.width=4, fig.height=4}
load("temp/SynchFV.RData")
d1 <- as.Date("2015-11-13")
dtbreaks <- c(d1 + seq(-4*7*8,0,by=7*8), d1 + seq(7*8,4*7*8,by=7*8))

Tts <- data.frame(date=pTS$date, mid=pTS$Tmid, low=pTS$Tlow, hi=pTS$Thi)
Fts <- data.frame(date=pTS$date, mid=pTS$Fmid, low=pTS$Flow, hi=pTS$Fhi)
plt <- plotts(Tts, nolog=TRUE,
              zero=FALSE, dtbreaks= "8 weeks", col="red", bgcolor = rgb(1,0,0,0.25))
plt <- plotts(Fts, col="blue", nolog=TRUE, add=TRUE, plt=plt, 
             bgcolor= rgb(0,0,1,0.25), zero=FALSE)

plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d")
plt

```

```{r EmoFVTSDif, cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE, fig.cap="French Value Synchronization", fig.width=8, fig.height=2.5}
load("temp/SynchFV.RData")
refTS <- pTS
load("temp/SynchDifFV.RData")
pTS$low <- pTS$low/refTS$Flow*100
pTS$mid <- pTS$mid/refTS$Fmid*100
pTS$hi <- pTS$hi/refTS$Fhi*100


plt <- plotts(pTS, nolog=TRUE,  bgcolor= rgb(0,0,0.5,0.25), col="darkblue",
              zero=TRUE)
plt <- plt + geom_vline(xintercept=as.numeric(as.Date("2015-11-27")))
plt <- plt + scale_x_date("Day", breaks = dtbreaks, date_labels = "%b %d", limits=c(as.Date("2015-06-30"), as.Date("2016-06-30")))
plt

```


## 4.2 Mediation analysis


```{r , cache=TRUE, eval=FALSE, echo=TRUE, message=FALSE}
library(mediation)
Nrep <- 10000

load("periodUserDF.RData")
periodUserDF %>% dplyr::select(avgEmo, PABL, NABL, socBL, iBL, nTBL) -> cDF
prelin <- glm(avgEmo ~ PABL+NABL+socBL+iBL+log(nTBL), data=cDF)

userDF <- periodUserDF
userDF$emo <- as.numeric(scale(userDF$avgEmo - predict(prelin, newdata=userDF)))
userDF$socBL <- as.numeric(scale(userDF$socBL))
userDF$prosocBL <- as.numeric(scale(userDF$prosocBL))
userDF$FVBL <- as.numeric(scale(userDF$FVBL))
userDF$PABL <- as.numeric(scale(userDF$PABL))
userDF$NABL <- as.numeric(scale(userDF$NABL))
userDF$iBL <- as.numeric(scale(userDF$iBL))
userDF$lnTBL <- as.numeric(scale(log(userDF$nTBL)))

userDF$socPost <- as.numeric(scale(userDF$socPost))
userDF$avgSoc <- as.numeric(scale(userDF$avgSoc))
med.fit <- glm(avgSoc ~ emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)
out.fit <- glm(socPost ~ avgSoc + emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)

med.soc <- mediate(med.fit, out.fit, treat = "emo", mediator = "avgSoc", control.value=quantile(userDF$emo, 0.25, na.rm=T), treat.value = quantile(userDF$emo, 0.75, na.rm=T), covariates=list("SocBL", "PABL","NABL","iBL","lnTBL"), boot = T, sims = Nrep)
save(med.soc, file="temp/med.soc.RData")

userDF$prosocPost <- as.numeric(scale(userDF$prosocPost))
userDF$avgProsoc <- as.numeric(scale(userDF$avgProsoc))
med.fit <- glm(avgProsoc ~ emo + prosocBL + PABL + NABL + iBL + lnTBL, data = userDF)
out.fit <- glm(prosocPost ~ avgProsoc + emo + prosocBL + PABL + NABL + iBL + lnTBL, data = userDF)

med.prosoc <- mediate(med.fit, out.fit, treat = "emo", mediator = "avgProsoc",  control.value=quantile(userDF$emo, 0.25, na.rm=T), treat.value = quantile(userDF$emo, 0.75, na.rm=T), covariates=list("prosocBL", "PABL","NABL","iBL","lnTBL"), boot = TRUE, sims = Nrep)
save(med.prosoc, file="temp/med.prosoc.RData")

userDF$FVPost <- as.numeric(scale(userDF$FVPost))
userDF$avgFV <- as.numeric(scale(userDF$avgFV))
med.fit <- glm(avgFV ~ emo + FVBL + PABL + NABL + iBL + lnTBL, data = userDF)
out.fit <- glm(FVPost ~ avgFV + emo + FVBL + PABL + NABL + iBL + lnTBL, data = userDF)

med.FV <- mediate(med.fit, out.fit, treat = "emo", mediator = "avgFV",  control.value=quantile(userDF$emo, 0.25, na.rm=T), treat.value = quantile(userDF$emo, 0.75, na.rm=T), covariates=list("FVBL", "PABL","NABL","iBL","lnTBL") , boot = TRUE, sims = Nrep)
save(med.FV, file="temp/med.FV.RData")

userDF$PAPost <- as.numeric(scale(userDF$PAPost))
userDF$avgPA <- as.numeric(scale(userDF$avgPA))
med.fit <- glm(avgPA ~ emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)
out.fit <- glm(PAPost ~ avgPA + emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)

med.PA <- mediate(med.fit, out.fit, treat = "emo", mediator = "avgPA", control.value=quantile(userDF$emo, 0.25, na.rm=T), treat.value = quantile(userDF$emo, 0.75, na.rm=T), boot = TRUE, sims = Nrep, covariates=list("socBL", "PABL","NABL","iBL","lnTBL"))
save(med.PA, file="temp/med.PA.RData")

userDF$NAPost <- as.numeric(scale(userDF$NAPost))
userDF$avgNA <-as.numeric(scale(userDF$avgNA))
med.fit <- glm(avgNA~ emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)
out.fit <- glm(NAPost ~ avgNA + emo + socBL + PABL + NABL + iBL + lnTBL, data = userDF)

med.NA <- mediate(med.fit, out.fit, treat = "emo", mediator = "avgNA", control.value=quantile(userDF$emo, 0.25, na.rm=T), covariates=list("prosocBL", "PABL","NABL","iBL","lnTBL"), treat.value = quantile(userDF$emo, 0.75, na.rm=T), boot= TRUE, sims = Nrep)
save(med.NA, file="temp/med.NA.RData")

```



```{r , cache=TRUE, eval=TRUE, echo=TRUE, message=FALSE}
library(mediation)
load("temp/med.soc.RData")
summary(med.soc)

load("temp/med.prosoc.RData")
summary(med.prosoc)

load("temp/med.FV.RData")
summary(med.FV)

load("temp/med.PA.RData")
summary(med.PA)

load("temp/med.NA.RData")
summary(med.NA)

```


